# See https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/

name: Fly Deploy

on:
  # trigger on push
  push:
    branches:
      - main
  # trigger on pull_request to the main branch
  pull_request:
    branches: [main]
    types: [opened, synchronize]

  
env:
  # the below will be 'true'
  CONDITION: ${{ contains(toJson(github.event.commits.*.message), '#skip') }}

    
jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Check style
      run: npm run eslint

    - name: Build
      run: npm run build
    - name: Test
      run: npm run test

    - name: e2e tests
      uses: cypress-io/github-action@v5
      with:
        command: npm run test:e2e
        start: npm run start-prod
        wait-on: http://localhost:5000
        
    - name: Deploy to Fly.io
      uses: superfly/flyctl-actions/setup-flyctl@master
    - run: flyctl deploy --remote-only
      env:
        # in settings in github added FLY_API_TOKEN from Fly
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      # only in case of pull request, false condition and succeeded previous steps, is app deployed 
      if: ${{ (github.event_name == 'push') && (env.CONDITION == 'false') && success() }}
      # added from https://github.com/marketplace/actions/discord-webhook-notify

    - name: Deployed Succeed
      # only in case of pull request, false condition and succeeded previous steps, it is notified about the success on discord 
      if: ${{ (github.event_name == 'push') && (env.CONDITION == 'false') && success() }}
      uses: rjstone/discord-webhook-notify@v1
      # run: echo "Deployed Succeed"
      with:
        severity: info
        username: tmshts
        color: green
        description: A new version of Pokedex deployed
        details: 'to https://fullstackopen--pokedex.fly.dev/ by tmshts'
        footer: 'Severity: Informational'
        webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

    - name: Deployed Failed
      # in case of failure of any previous steps
      if: failure()
      uses: rjstone/discord-webhook-notify@v1
      with:
        severity: error
        username: tmshts
        color: red
        description: Build Failed
        details: commit https://github.com/tmshts/full-stack-open-pokedex/commit/${{ (github.event.after) }} by tmshts broke during check before merging pull request
        footer: 'Severity: Error'
        webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
    
  tag_release:
    # dependency -> run after simple_deployment_pipeline is executed
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-20.04
    steps:
    - name: Bump version and push tag
      uses: actions/checkout@v4
    - name: Tag
      uses: anothrNick/github-tag-action@8c8163ef62cf9c4677c8e800f36270af27930f42
     # uses: anothrNick/github-tag-action@1.71.0
      env:
        # since it is a third party it needs token for authentication 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # bumb the patch versioning
        DEFAULT_BUMP: patch
      # only in case of pull request is app deployed 
      if: ${{ (github.event_name == 'push') && (env.CONDITION == 'false') }}
      
      
