# See https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/

name: Fly Deploy

on:
  # trigger on push
  push:
    branches:
      - main
  # trigger on pull_request to the main branch
  pull_request:
    branches: [main]
    types: [opened, synchronize]
    
jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Check style
      run: npm run eslint

    - name: Build
      run: npm run build
    - name: Test
      run: npm run test

    - name: e2e tests
      uses: cypress-io/github-action@v5
      with:
        command: npm run test:e2e
        start: npm run start-prod
        wait-on: http://localhost:5000
        
    - uses: actions/checkout@v4
    - uses: superfly/flyctl-actions/setup-flyctl@master
    - run: flyctl deploy --remote-only
      env:
        # in settings in github added FLY_API_TOKEN from Fly
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      # only in case of pull request is app deployed 
      if: ${{ github.event_name == 'push' }}
    
  tag_release:
    # dependency -> run after simple_deployment_pipeline is executed
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-20.04
    steps:
    - name: Bump version and push tag
      uses: actions/checkout@v4
    - name: Tag
      uses: anothrNick/github-tag-action@1.71.0
      env:
        # since it is a third party it needs token for authentication 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # bumb the patch versioning
        DEFAULT_BUMP: patch
      # only in case of pull request is app deployed 
      if: ${{ github.event_name == 'push' }}
      

