name: Testing stuff

on:
  push:
    branches:
      - main

env:
  # the below will be 'true'
  CONDITION: ${{ contains(toJson(github.event.commits.*.message), '#skip') }}
  COMPARE: 'compare'


jobs:
  a_test_job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: commits
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
        run: echo "$COMMITS"
      - name: commit messages
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
        run: echo "$COMMIT_MESSAGES"
      - if: ${{ env.CONDITION == 'true'}}
        run: echo 'found'
      - if: ${{ env.CONDITION == 'false'}}
        run: echo 'not found'


  dependent_job:
    needs: [a_test_job]
    runs-on: ubuntu-20.04
    steps:
        - uses: actions/checkout@v4
        - name: github deploy
          run: echo 'test dependent_job'
        - if: ${{ (env.CONDITION == 'true') && (env.COMPARE == 'compare') }}
          run: echo 'dependent_job executed because of true condition'
        - if: ${{ env.CONDITION == 'false' }}
          run: echo 'dependent_job not executed because of false condition'